### ISSUE TITLE
Installed CSS-size but it's not working

### ISSUE THREAD

**Issue by jitendravyas** [ben-eb/css-size#31]
`npm install css-size --save` went successful

```
css-size --help
zsh: command not found: css-size
```

Node version - v6.10.0

**Comment by ben-eb** [comment]
@jitendravyas I have this in my `~/.bash_profile` which adds local node binaries to your `$PATH` automatically, rather than using a global install:

```
export PATH=$PATH:./node_modules/.bin
```

Does this help?

**Comment by jitendravyas** [comment]
I use ZSH

**Comment by ben-eb** [comment]
Works for zsh too. There's a module you can install that runs this task: https://www.npmjs.com/package/add-local-binaries-to-path

**Comment by jitendravyas** [comment]
Installed this tool but problem is still there

**Comment by jitendravyas** [comment]
this helped as u suggested `export PATH=$PATH:./node_modules/.bin`
